---
- name: ensure iptables can be loaded properly
  sudo: true
  apt: pkg=iptables-persistent

- name: enable ip packet forwarding permanently
  sudo: true
  lineinfile: dest=/etc/sysctl.conf regexp='#?net.ipv4.ip_forward=.*' line='net.ipv4.ip_forward=1' state=present
  register: result

- name: enable ip packet forwarding for current session
  sudo: true
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward
  when: result|changed

